# Generated by Django 5.2.1 on 2025-06-13 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 10, 6, 0, 896964)),
        ),
        migrations.AlterField(
            model_name='videouser',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 10, 6, 0, 895618)),
        ),
    ]
