# Generated by Django 5.2.1 on 2025-06-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videouser',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videouser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profilePictures/<django.db.models.fields.CharField>/'),
        ),
    ]
