# Generated by Django 5.2.1 on 2025-06-18 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_video_date_alter_videouser_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 14, 36, 59, 643194)),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='videouser',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 14, 36, 59, 641868)),
        ),
    ]
