# Generated by Django 5.2.1 on 2025-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_video_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='videos',
            field=models.ManyToManyField(blank=True, to='models.video'),
        ),
    ]
